load("@rules_shell//shell:sh_binary.bzl", "sh_binary")
load("//programs/arca:defs.bzl", "ARCA_COMBINATORS", "ARCA_PROGRAMS")
load("//programs/fix:defs.bzl", "FIX_PROGRAMS", "FIX_RUST_PROGRAMS")
load("//programs/kernel:defs.bzl", "KERNEL_PROGRAMS")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "artifacts",
    srcs = [
        "//fix/runtime:image",
        "//programs/arca:webserver",
        "//programs/arca:webserver2",
        "//programs/fix/parser:parser",
        "//tools/vmm",
    ] + ["//programs/arca:" + name for name in ARCA_PROGRAMS] + [
        "//programs/arca:" + name + "_elf" for name in ARCA_COMBINATORS
    ] + [
        "//programs/fix:" + name for name in FIX_PROGRAMS + FIX_RUST_PROGRAMS
    ] + ["//programs/kernel:" + name + "_image" for name in KERNEL_PROGRAMS],
)

test_suite(
    name = "host_tests",
    tests = [
        "//arca/api:tests",
        "//fix/handle:tests",
        "//lib/common:tests",
        "//tools/vmm:tests",
        "//tools:postprocess_test",
    ],
)

test_suite(
    name = "guest_tests",
    tags = ["kvm"],
    tests = [
        "//arca/kernel:tests",
        "//fix/runtime:tests",
        "//programs/kernel:hello_test",
        "//programs/kernel:threads_test",
        "//tests/fix:tests",
    ],
)

sh_binary(
    name = "format",
    srcs = ["//tools:format.sh"],
)
