load("@rules_rust//rust:defs.bzl", "rust_shared_library")
load("//build:defs.bzl", "WASM", "fix_procedure")

package(default_visibility = ["//visibility:private"])

rust_shared_library(
    name = "wasm",
    visibility = ["//tests:__pkg__"],
    srcs = glob(["src/**/*.rs"]),
    crate_name = "fixparser",
    crate_root = "src/lib.rs",
    platform = WASM,
    deps = [
        "//fix/sdk",
        "@crates//:dlmalloc",
        "@crates//:hex",
    ],
)

fix_procedure(
    name = "parser",
    visibility = ["//visibility:public"],
    artifact_visibility = ["//fix/runtime:__pkg__"],
    postprocess = True,
    runnable = True,
    wasm = ":wasm",
)
