load("@rules_rust//rust:defs.bzl", "rust_library")
load("//build:defs.bzl", "GUEST_ONLY", "kernel_program", "kernel_test")

package(default_visibility = ["//visibility:private"])

DEPS = [
    "//arca/api",
    "//arca/kernel",
    "//arca/abi",
    "//lib/common",
    "//fix/handle",
    "@crates//:log",
    "@crates//:serde",
    "@crates//:postcard",
    "@crates//:derive_more",
    "@crates//:async-lock",
    "@crates//:hex",
    "@crates//:bitint",
    "@crates//:blake3",
    "@crates//:crossbeam-queue",
]

rust_library(
    name = "runtime",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = [
            "src/main.rs",
            "src/name.rs",
            "src/parallel_evaluator.rs",
            "src/scheduler.rs",
            "src/testing.rs",
        ],
    ),
    compile_data = ["//programs/fix:identity_elf"],
    crate_name = "fix",
    proc_macro_deps = ["//tools/macros"],
    rustc_env = {"FIX_IDENTITY": "$(execpath //programs/fix:identity_elf)"},
    target_compatible_with = GUEST_ONLY,
    deps = DEPS,
)

[
    rule(
        name = "tests" if test else "image",
        visibility = ["//:__pkg__"] if test else ["//visibility:public"],
        image_visibility = ["//tests:__pkg__"] if test else [
            "//tests:__subpackages__",
            "//programs/fix:__subpackages__",
            "//coupon:__pkg__",
        ],
        image_name = "test_image" if test else "image_elf",
        srcs = [
            "src/main.rs",
            "src/parallel_evaluator.rs",
            "src/scheduler.rs",
            "src/testing.rs",
        ],
        compile_data = ["//programs/fix/parser:parser_elf"],
        crate_name = "fix",
        crate_root = "src/main.rs",
        linker_script = "etc/memmap.ld",
        proc_macro_deps = ["//tools/macros"],
        rustc_env = {"FIX_PARSER": "$(execpath //programs/fix/parser:parser_elf)"},
        deps = [":runtime"] + DEPS,
    )
    for test, rule in [(False, kernel_program), (True, kernel_test)]
]

alias(
    name = "fix",
    visibility = ["//visibility:public"],
    actual = ":image",
)
