(module
  (import "fix" "attach_tree" (func $attach_tree (param externref i32)))
  (import "fix" "detach_tree" (func $detach_tree (param i32 i32)))
  (import "fix" "len" (func $len (param externref) (result i32)))
  (import "fix" "equals" (func $equals (param externref externref) (result i32)))
  (import "fix" "create_tree" (func $create_tree (param i32 i32) (result externref)))
  (import "fix" "is_object" (func $object (param externref) (result i32)))
  (import "fix" "is_blob_obj" (func $blob (param externref) (result i32)))
  (table $scratch 0 externref)
  (func $entry (param $tree externref) (param $index i32) (result externref)
    (local $value externref)
    (call $attach_tree (local.get $tree) (i32.const 0))
    (local.set $value (table.get $scratch (local.get $index)))
    (call $detach_tree (i32.const 0) (i32.const 0))
    (local.get $value))
  (func $tree_length (param $tree externref) (result i32)
    (if (i32.eqz (call $object (local.get $tree))) (then unreachable))
    (if (call $blob (local.get $tree)) (then unreachable))
    (call $len (local.get $tree)))
  (func $field (param $descriptor externref) (param $index i32) (result externref)
    (if (i32.ne (call $tree_length (local.get $descriptor)) (i32.const 3)) (then unreachable))
    (call $entry (local.get $descriptor) (local.get $index)))
  (func $apply (export "_fix_apply") (param $combination externref) (result externref)
    (local $descriptor externref) (local $path externref) (local $wanted externref)
    (local $children externref) (local $child externref)
    (local $component i32) (local $index i32) (local $count i32) (local $entries i32)
    (local.set $descriptor (call $entry (local.get $combination) (i32.const 1)))
    (if (i32.eqz (call $tree_length (local.get $descriptor)))
      (then (return (local.get $descriptor))))
    (if (i32.ne (call $tree_length (local.get $descriptor)) (i32.const 3)) (then unreachable))
    (local.set $path (call $entry (local.get $combination) (i32.const 2)))
    (local.set $count (call $tree_length (local.get $path)))
    (block $done (loop $next_component
      (br_if $done (i32.eq (local.get $component) (local.get $count)))
      (local.set $wanted (call $entry (local.get $path) (local.get $component)))
      (local.set $children (call $field (local.get $descriptor) (i32.const 2)))
      (local.set $entries (call $tree_length (local.get $children)))
      (local.set $index (i32.const 0))
      (block $found (loop $next_child
        (if (i32.eq (local.get $index) (local.get $entries))
          (then (return (call $create_tree (i32.const 0) (i32.const 0)))))
        (local.set $child (call $entry (local.get $children) (local.get $index)))
        (if (call $equals (call $field (local.get $child) (i32.const 0)) (local.get $wanted))
          (then (local.set $descriptor (local.get $child)) (br $found)))
        (local.set $index (i32.add (local.get $index) (i32.const 1)))
        (br $next_child)))
      (local.set $component (i32.add (local.get $component) (i32.const 1)))
      (br $next_component)))
    (local.get $descriptor))
)
