load("@rules_rust//rust:defs.bzl", "rust_clippy_test", "rustfmt_test")
load("//programs/arca:defs.bzl", "ARCA_COMBINATORS", "ARCA_PROGRAMS")
load("//programs/kernel:defs.bzl", "KERNEL_PROGRAMS")
load("//programs/fix:defs.bzl", "FIX_RUST_PROGRAMS")

HOST = [
    "//tools/vmm:vmm",
    "//tools:bindgen",
    "//tools:postprocess",
    "//fix/handle",
    "//coupon:api",
]

GUEST = [
    "//fix/runtime:image_elf",
    "//arca/kernel:test_image",
    "//fix/runtime:test_image",
    "//programs/arca:simd_elf",
] + ["//programs/kernel:" + name + "_image" for name in KERNEL_PROGRAMS] + [
    "//programs/arca:" + name + "_elf" for name in ARCA_PROGRAMS + ARCA_COMBINATORS + ["webserver", "webserver2"]
] + [
    "//programs/arca:" + name + "_image" for name in ARCA_PROGRAMS
]

CHECKS = HOST + GUEST + ["//programs/fix/parser:wasm"] + [
    "//programs/fix:" + name + "_wasm" for name in FIX_RUST_PROGRAMS
]

rustfmt_test(
    name = "rust_format",
    tags = ["manual"],
    targets = CHECKS,
    transitive = True,
)

rust_clippy_test(
    name = "rust_lint",
    tags = ["manual"],
    targets = CHECKS,
    transitive = True,
)

test_suite(name = "format", tags = ["manual"], tests = [":rust_format", "//fix/sdk:format_test"])
test_suite(name = "lint", tags = ["manual"], tests = [":rust_lint", "//fix/sdk:lint"])
