load(":defs.bzl", "FIX_PROGRAMS", "fix_rust_program", "fix_wat_program")

package(default_visibility = ["//visibility:private"])

[fix_wat_program(name = name) for name in FIX_PROGRAMS]
fix_rust_program(name = "map")
fix_rust_program(name = "mapreduce")
fix_rust_program(name = "fib")
fix_rust_program(name = "count_words", alloc = True)
fix_rust_program(name = "bptree_get", alloc = True)
fix_rust_program(name = "bptree_get_n", alloc = True)
