  (func $is_coupon (param $tag externref) (param $type i32) (result i32) 
    (call $is_tag (local.get $tag))
    (if (result i32)
      (then
        ;; Attach the tag
        (call $attach_tree (i32.const 1) (local.get $tag))
        ;; Check if the tag was authored by us
        (call $is_equal (table.get $encode (i32.const 0)) (table.get $coupon_scratch (i32.const 0)))
        (if (result i32)
          (then
            ;; Check if the coupon type matches the input type
            (call $attach_blob (i32.const 1) (table.get $coupon_scratch (i32.const 1)))
            (i32.load (memory $mem_1) (i32.const 0))
            (local.get $type)
            i32.eq
            (if (result i32)
              (then (i32.const 1))
              (else (i32.const 0))
            )
          )
          (else (i32.const 0))
        )
      )
      (else (i32.const 0))
    )
  )
  (func $is_eq_coupon (param $tag externref) (result i32)
    (call $is_coupon (local.get $tag) (global.get $Eq))
  )
  (func $is_eval_coupon (param $tag externref) (result i32)
    (call $is_coupon (local.get $tag) (global.get $Eval))
  )
  (func $is_apply_coupon (param $tag externref) (result i32)
    (call $is_coupon (local.get $tag) (global.get $Apply))
  )
  (func $is_force_coupon (param $tag externref) (result i32)
    (call $is_coupon (local.get $tag) (global.get $Force))
  )
  (func $is_think_coupon (param $tag externref) (result i32)
    (call $is_coupon (local.get $tag) (global.get $Think))
  )
  (func $is_storage_coupon (param $tag externref) (result i32)
    (call $is_coupon (local.get $tag) (global.get $Storage))
  )
  (func $create_coupon (param $type i32) (param $lhs externref) (param $rhs externref) (result externref)
    (table.set $output_coupon_scratch (i32.const 0) (table.get $encode (i32.const 0)))
    (table.set $output_coupon_scratch (i32.const 1) (call $create_blob_i32 (local.get $type)))
    (table.set $output_coupon_scratch (i32.const 2) (local.get $lhs))
    (table.set $output_coupon_scratch (i32.const 3) (local.get $rhs))
    (call $create_tag (i32.const 5))
  )
  (func $create_eq_coupon (param $lhs externref) (param $rhs externref) (result externref)
    (call $create_coupon (global.get $Eq) (local.get $lhs) (local.get $rhs))
  )
  (func $create_eval_coupon (param $lhs externref) (param $rhs externref) (result externref)
    (call $create_coupon (global.get $Eval) (local.get $lhs) (local.get $rhs))
  )
  (func $create_force_coupon (param $lhs externref) (param $rhs externref) (result externref)
    (call $create_coupon (global.get $Force) (local.get $lhs) (local.get $rhs))
  )
  (func $create_think_coupon (param $lhs externref) (param $rhs externref) (result externref)
    (call $create_coupon (global.get $Think) (local.get $lhs) (local.get $rhs))
  )
  (func $get_coupon_lhs (param $coupon externref) (result externref)
    (call $attach_tree (i32.const 1) (local.get $coupon))
    (table.get $coupon_scratch (i32.const 2))
  )
  (func $get_coupon_rhs (param $coupon externref) (result externref)
    (call $attach_tree (i32.const 1) (local.get $coupon))
    (table.get $coupon_scratch (i32.const 3))
  )
  (func $get_tree_size (param $t externref) (result i32)
    (call $attach_tree (i32.const 3) (local.get $t))
    table.size $tree_scratch
  )
  (func $get_tree_data (param $t externref) (param $i i32) (result externref) 
    (call $attach_tree (i32.const 3) (local.get $t))
    (table.get $tree_scratch (local.get $i))
  )
  (func (export "_fixpoint_apply") (param $combination externref) (result externref)
    ;; attach combination tree
    (call $attach_tree
          (i32.const 0)
          (local.get $combination))
    ;; attach coupons
    (call $attach_tree
          (i32.const 2)
          (table.get $encode (i32.const 2)))
    ;; attach request field
    (call $attach_blob
          (i32.const 1)
          (table.get $encode (i32.const 1)))
    (call $make_coupon
          (i32.load $mem_1 (i32.const 0))
          (table.get $encode (i32.const 3))
          (table.get $encode (i32.const 4))
    )
  )
