  (import "fixpoint" "is_equal" (func $is_equal (param externref) (param externref) (result i32)))
  (import "fixpoint" "is_tag" (func $is_tag (param externref) (result i32)))
  (import "fixpoint" "attach_blob" (func $attach_blob (param i32) (param externref)))
  (import "fixpoint" "attach_tree" (func $attach_tree (param i32) (param externref)))
  (import "fixpoint" "create_blob_i32" (func $create_blob_i32 (param i32) (result externref)))
  (import "fixpoint" "create_tag" (func $create_tag (param i32) (result externref)))
  (import "fixpoint" "create_application_thunk" (func $create_application_thunk (param externref) (result externref)))
  (import "fixpoint" "create_strict_encode" (func $create_strict_encode (param externref) (result externref)))
  (import "fixpoint" "create_shallow_encode" (func $create_shallow_encode (param externref) (result externref)))
  (import "fixpoint" "is_blob_obj" (func $is_blob_obj (param externref) (result i32)))
  (import "fixpoint" "is_data" (func $is_data (param externref) (result i32)))
  (import "fixpoint" "is_object" (func $is_object (param externref) (result i32)))
  (table $encode 0 externref)
  (table $coupon_scratch 0 externref)
  (table $coupons 0 externref)
  (table $tree_scratch 0 externref)
  (table $output_coupon_scratch 4 externref)
  (memory $mem_0 0)
  (memory $mem_1 0)
  (global $Eq i32 (i32.const 0))
  (global $Eval i32 (i32.const 1))
  (global $Apply i32 (i32.const 2))
  (global $Force i32 (i32.const 3))
  (global $Think i32 (i32.const 4))
  (global $Storage i32 (i32.const 5))
