load("@rules_rust//rust:defs.bzl", "rust_library")
load("//build:defs.bzl", "GUEST_ONLY", "kernel_test", "native_archive")

package(default_visibility = ["//visibility:private"])

DEPS = [
    "//arca/abi",
    "//arca/api",
    "//lib/common",
    "@crates//:async-lock",
    "@crates//:hashbrown",
    "@crates//:log",
    "@crates//:postcard",
    "@crates//:serde",
    "@crates//:time",
]

PROC_MACROS = [
    "//tools/macros",
    "@crates//:bitfield-struct",
]

exports_files(["etc/memmap.ld"], visibility = ["//programs:__subpackages__", "//fix/runtime:__pkg__"])

native_archive(
    name = "assembly",
    srcs = [
        "src/cswitch.S",
        "src/interrupts.S",
        "src/util.S",
    ],
)

rust_library(
    name = "kernel",
    visibility = ["//visibility:public"],
    srcs = glob(["src/**/*.rs"]),
    link_deps = [":assembly"],
    proc_macro_deps = PROC_MACROS,
    target_compatible_with = GUEST_ONLY,
    deps = DEPS,
)

kernel_test(
    name = "tests",
    visibility = ["//:__pkg__"],
    image_visibility = ["//tests:__pkg__"],
    image_name = "test_image",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "kernel",
    crate_root = "src/lib.rs",
    link_deps = [":assembly"],
    linker_script = "etc/memmap.ld",
    proc_macro_deps = PROC_MACROS,
    compile_data = ["//programs/arca:simd_elf"],
    rustc_env = {"ARCA_SIMD_PROGRAM": "$(execpath //programs/arca:simd_elf)"},
    deps = DEPS,
)
