load("@rules_rust//rust:defs.bzl", "rust_library", "rust_shared_library")
load("//build:cc.bzl", "cc_object")
load("//build:cc_checks.bzl", "cc_format", "cc_lint_test")
load("//build:defs.bzl", "WASM", "fix_procedure", "vm_test", "wasm_library")
load(":defs.bzl", "SDK_WARNINGS", "fix_cc_wasm", "sdk_copts")

package(default_visibility = ["//visibility:public"])

exports_files(["defs.bzl"])

cc_format(
    name = "format",
    srcs = glob(["include/*.h", "src/*.c", "tests/*.c"]),
    style = ".clang-format",
)

cc_lint_test(
    name = "c_lint_test",
    srcs = glob(["src/*.c", "tests/*.c"]),
    hdrs = [":headers"],
    config = ".clang-tidy",
    copts = sdk_copts() + SDK_WARNINGS,
)

test_suite(name = "lint", tests = [":c_lint_test"])

filegroup(
    name = "headers",
    srcs = glob(["include/*.h"]),
)

rust_library(
    name = "types",
    srcs = ["src/types.rs"],
    crate_name = "fixtypes",
)

cc_object(
    name = "rust_c",
    src = "src/rust.c",
    hdrs = [":headers"],
    compiler = "@local_tools//:clang",
    copts = sdk_copts() + SDK_WARNINGS,
)

wasm_library(
    name = "rust_runtime",
    srcs = [":rust_c"],
    target_compatible_with = ["@platforms//cpu:wasm32"],
)

[
    rust_library(
        name = name,
        srcs = glob(["src/**/*.rs"]),
        crate_name = "fix",
        crate_features = features,
        deps = [":types"],
        link_deps = [":rust_runtime"],
        proc_macro_deps = ["//tools/macros"],
        target_compatible_with = ["@platforms//cpu:wasm32"],
    )
    for name, features in [("sdk", []), ("sdk_alloc", ["alloc"])]
]

fix_cc_wasm(
    name = "c_bindings_wasm",
    srcs = ["tests/bindings.c"],
    memories = 3,
    tables = 4,
    copts = SDK_WARNINGS,
)

rust_shared_library(
    name = "rust_files_wasm",
    srcs = ["tests/rust_files.rs"],
    platform = WASM,
    edition = "2024",
    deps = [":sdk"],
)

[
    fix_procedure(
        name = name + "_native",
        wasm = ":" + name + "_wasm",
        memories = 2 if name == "rust_files" else None,
        tables = 2 if name == "rust_files" else None,
    )
    for name in ["c_bindings", "rust_files"]
]

[
    vm_test(
        name = name + "_test",
        size = "large",
        timeout = "short",
        args = ["eval", name + ".fix"],
        data = [":" + name + "_native", "tests/" + name + ".fix"],
        expected_output = ["as a u64: 42"],
        kernel = "//fix/runtime:image_elf",
        tags = ["kvm", "local"],
    )
    for name in ["c_bindings", "rust_files"]
]

test_suite(name = "tests", tests = [":c_bindings_test", ":rust_files_test"])
