extern crate cbindgen;

use anyhow::Result;
use std::env;

fn main() -> Result<()> {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    println!("cargo::rustc-link-arg=-no-pie");

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_no_includes()
        .with_language(cbindgen::Language::C)
        .with_autogen_warning("/*Automatically generated by cbindgen*/")
        .with_sys_include("immintrin.h")
        .with_sys_include("stdint.h")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(format!("{}/../fix-shell/bindings.h", crate_dir));

    Ok(())
}
