load("//build:defs.bzl", "vm_test")
load("//programs/fix:defs.bzl", "FIX_RUST_PROGRAMS")

package(default_visibility = ["//visibility:public"])

exports_files(glob(["*.fix"]))

[
    genrule(
        name = name + "_fixture",
        visibility = ["//visibility:private"],
        srcs = ["//programs/fix:" + name + "_elf"],
        outs = [name],
        cmd = "cp $< $@",
    )
    for name in ["addblob"] + FIX_RUST_PROGRAMS
]

vm_test(
    name = "addblob_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "addblob.fix",
    ],
    data = [
        "addblob.fix",
        ":addblob_fixture",
    ],
    expected_output = ["as a u64: 6"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "addblob_extended_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "addblob_extended.fix",
    ],
    data = [
        "addblob_extended.fix",
        ":addblob_fixture",
    ],
    expected_output = ["as a u64: 136"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "selection_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "selection.fix",
    ],
    data = ["selection.fix"],
    expected_output = ["result is a Blob: [104]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "parallel_addblob_test",
    size = "large",
    timeout = "short",
    args = [
        "parallel_eval",
        "addblob.fix",
    ],
    data = [
        "addblob.fix",
        ":addblob_fixture",
    ],
    expected_output = ["as a u64: 6"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "bptree_get_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "bptree_get.fix",
    ],
        data = [
        "bptree_get.fix",
        ":bptree_get_fixture",
    ],
    expected_output = ["result is a Blob: [54]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "bptree_get_n_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "bptree_get_n.fix",
    ],
        data = [
        "bptree_get_n.fix",
        ":bptree_get_n_fixture",
    ],
    expected_output = ["result is a Blob: [53]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "map_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "map.fix",
    ],
    data = [
        "map.fix",
        ":addblob_fixture",
        ":map_fixture",
    ],
    expected_output = ["result is a Blob: [10, 0, 0, 0, 0, 0, 0, 0]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "mapreduce_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "mapreduce.fix",
    ],
    data = [
        "mapreduce.fix",
        ":addblob_fixture",
        ":count_words_fixture",
        ":mapreduce_fixture",
    ],
    expected_output = ["result is a Blob: [4, 0, 0, 0, 0, 0, 0, 0]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "count_words_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "count_words.fix",
    ],
    data = [
        "count_words.fix",
        ":count_words_fixture",
    ],
    expected_output = ["result is a Blob: [2, 0, 0, 0, 0, 0, 0, 0]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

vm_test(
    name = "fib_test",
    size = "large",
    timeout = "short",
    args = [
        "eval",
        "fib.fix",
    ],
    data = [
        "fib.fix",
        ":addblob_fixture",
        ":fib_fixture",
    ],
    expected_output = ["result is a Blob: [13, 0, 0, 0, 0, 0, 0, 0]"],
    kernel = "//fix/runtime:image_elf",
    tags = [
        "kvm",
        "local",
    ],
)

test_suite(
    name = "tests",
    tests = [
        ":addblob_extended_test",
        ":addblob_test",
        ":bptree_get_n_test",
        ":bptree_get_test",
        ":count_words_test",
        ":fib_test",
        ":map_test",
        ":mapreduce_test",
        ":parallel_addblob_test",
        ":selection_test",
    ],
)
