(module
  (import "fix" "attach_tree" (func $attach (param externref i32)))
  (import "fix" "is_blob_obj" (func $blob (param externref) (result i32)))
  (import "fix" "is_object" (func $object (param externref) (result i32)))
  (import "fix" "len" (func $len (param externref) (result i32)))
  (import "fix" "create_blob_i64" (func $integer (param i64) (result externref)))
  (table $input 0 externref)
  (func (export "_fix_apply") (param $combination externref) (result externref)
    (local $result externref)
    (call $attach (local.get $combination) (i32.const 0))
    (local.set $result (table.get $input (i32.const 1)))
    (if (i32.eqz (call $object (local.get $result))) (then unreachable))
    (if (call $blob (local.get $result)) (then unreachable))
    (if (call $len (local.get $result)) (then unreachable))
    (call $integer (i64.const 42))))
