/*Automatically generated by cbindgen*/

#include <immintrin.h>
#include <stdint.h>
#include <string.h>

typedef struct { uint8_t bytes[32]; } bytes32;
typedef unsigned char __attribute__((vector_size(32))) u8x32;

static inline bytes32 bytes32_from_u8x32(u8x32 v) {
    bytes32 out;
    // memcpy is safest: no alignment assumptions
    memcpy(out.bytes, &v, 32);
    return out;
}

static inline u8x32 u8x32_from_bytes32(bytes32 b) {
    u8x32 out;
    memcpy(&out, b.bytes, 32);
    return out;
}

bytes32 fixpoint_create_blob_i64(uint64_t val);

uint64_t fixpoint_attach_blob(void *addr, bytes32 handle);

uint64_t fixpoint_attach_tree(void *addr, bytes32 handle);

bytes32 arca_blob_to_handle(int64_t h);

int64_t handle_to_arca_blob(bytes32 h);
