/*Automatically generated by cbindgen*/

#include <immintrin.h>
#include <stdint.h>

__m256i fixpoint_create_blob_i64(uint64_t val);

uint64_t fixpoint_attach_blob(void *addr, __m256i handle);

uint64_t fixpoint_attach_tree(void *addr, __m256i handle);

__m256i arca_blob_to_handle(int64_t h);

int64_t handle_to_arca_blob(__m256i h);
