load(":defs.bzl", "ARCA_COMBINATORS", "ARCA_PROGRAMS", "arca_elf", "arca_program")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

package(default_visibility = ["//visibility:private"])

[arca_program(name = name) for name in ARCA_PROGRAMS]

[arca_elf(name = name, visibility = ["//visibility:public"]) for name in ARCA_COMBINATORS]

[
    arca_elf(
        name = name,
        visibility = ["//programs/kernel:__pkg__", "//tests:__pkg__"],
    )
    for name in ["webserver", "webserver2"]
]

sh_test(
    name = "tests",
    visibility = ["//:__pkg__"],
    srcs = ["tests.sh"],
    args = ["$(rootpath :" + name + ")" for name in ["add", "identity", "null", "io"]],
    data = [":" + name for name in ARCA_PROGRAMS],
    size = "large",
    timeout = "short",
    tags = ["kvm", "local"],
)

[
    alias(
        name = name,
        visibility = ["//visibility:public"],
        actual = "//programs/kernel:" + name,
    )
    for name in ["webserver", "webserver2"]
]
