load("//build:defs.bzl", "ARCA_USER", "guest_binary")
load(":defs.bzl", "ARCA_PROGRAMS", "arca_program")

package(default_visibility = ["//visibility:private"])

[arca_program(name = name) for name in ARCA_PROGRAMS]

[
    guest_binary(
        name = name + "_elf",
        visibility = ["//programs/kernel:__pkg__", "//tests:__pkg__"],
        srcs = ["src/" + name + ".rs"],
        linker_script = "//arca/user:etc/memmap.ld",
        platform = ARCA_USER,
        deps = [
            "//arca/abi",
            "//arca/api",
            "//arca/user",
        ],
    )
    for name in ["webserver", "webserver2"]
]

[
    alias(
        name = name,
        visibility = ["//visibility:public"],
        actual = "//programs/kernel:" + name,
    )
    for name in ["webserver", "webserver2"]
]
