load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "api",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "alloc",
        "serde",
    ],
    crate_name = "arca",
    deps = ["@crates//:serde"],
)

rust_test(
    name = "tests",
    crate = ":api",
    crate_features = [
        "alloc",
        "serde",
    ],
)
