load("@rules_rust//rust:defs.bzl", "rust_library")
load("//build:defs.bzl", "GUEST_ONLY", "native_archive")

package(default_visibility = ["//visibility:private"])

exports_files(["etc/memmap.ld"], visibility = ["//programs/arca:__pkg__", "//tests/arca:__pkg__", "//fix/shell:__pkg__"])

native_archive(
    name = "start",
    srcs = ["src/start.S"],
)

rust_library(
    name = "user",
    visibility = ["//visibility:public"],
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["allocator"],
    link_deps = [":start"],
    target_compatible_with = GUEST_ONLY,
    deps = [
        "//arca/abi",
        "//arca/api",
        "@crates//:spin",
        "@crates//:talc",
    ],
)
