[package]
name = "vmm"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
kvm-bindings = { version = "0.14.1" }
kvm-ioctls = "0.25.0"
arca = { path = "../arca" }
common = { path = "../common" }
elf = "0.8.0"
env_logger = "0.11.11"
log = "0.4.34"
rustc-demangle = "0.1.28"
anyhow = "1.0.104"
libc = "0.2.189"
vmm-sys-util = "0.15.0"
ctrlc = "3.5.2"
regex = "1.13.1"
nix = { version = "0.31.3", features = ["mman", "socket"] }
clap = { version = "4.6.6", features = ["derive", "env"] }
postcard = { version = "1.1.3", features = ["use-std"] }
serde = "1.0.229"

# [dev-dependencies]
# kernel = { path = "../kernel", artifact = "bin", target = "x86_64-unknown-none" }
