[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", features = ["derive"] }
loader = { path = "../loader", artifact = "bin", target="i686-unknown-none" }
tempfile = "3.10.1"
